# Installs and Configures Nova
---

- name: Ensure Cinder is installed
  apt: name={{ item }} state=present
  with_items:
    - cinder-api
    - cinder-scheduler
    - cinder-volume
    - python-cinderclient

- name: Remove SQLite db file
  file: path=/var/lib/cinder/cinder.sqlite state=absent

