# installs the things i need for the openstack controller node
- include: base-services.yml
- include: keystone-base.yml
- include: glance.yml
- include: nova.yml
- include: neutron.yml
- include: horizon.yml
- include: cinder.yml
