# installs the things i need for the openstack controller node
# MariaDB hints: https://mariadb.com/blog/devops-mariadb-part-1
---
- name: Ensure MariaDB Server/Client/Lib is installed
  apt: name={{ item }} state=present
  with_items:
    - mariadb-server
    - mariadb-client
    - python-mysqldb

- name: Create user
  mysql_user: name=root host="%" password="Cisco.123" priv=*.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP state=present

- name: Make sure My.cnf is there. 
  copy: >
      src=../files/my.cnf
      dest=/etc/mysql/my.cnf
  #notify:
  #  - Restart MariaDB

- name: Restart MariaDB
  service: name=mysql state=restarted
