# Configures Neutron Users
---

- name: Ensure neutron user is created
  keystone_user: user=neutron tenant=service password={{ neutron_admin_password }} token={{ admin_token }} endpoint=http://{{ inventory_hostname }}:35357/v2.0

- name: Ensure neutron user role is ready
  keystone_user: user=neutron tenant=service role=admin token={{ admin_token }} endpoint=http://{{ inventory_hostname }}:35357/v2.0


