---

#
# Copyright (c) 2014 Davide Guerri <davide.guerri@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Modified by vallard@benincosa.com

- name: Configure Nova
  ini_file: dest=/etc/nova/nova.conf
            section="{{ item.section }}"
            option="{{ item.option }}"
            value="{{ item.value }}"
  with_items:
    - section:  DEFAULT
      option:   my_ip
      value:    "{{ inventory_hostname }}"
    - section:  DEFAULT
      option:   vnceserver_listen
      value:    "{{ inventory_hostname }}"
    - section:  DEFAULT
      option:   vncserver_proxy_client_address
      value:    "{{ inventory_hostname }}"
    - section:  DEFAULT
      option:   dhcpbridge_flagfile
      value:    /etc/nova/nova.conf
    - section:  DEFAULT
      option:   dhcpbridge
      value:    /usr/bin/nova-dhcpbridge
    - section:  DEFAULT
      option:   logdir
      value:    /var/log/nova
    - section:  DEFAULT
      option:   state_path
      value:    /var/lib/nova
    - section:  DEFAULT
      option:   lock_path
      value:    /var/lock/nova
    - section:  DEFAULT
      option:   force_dhcp_release
      value:    True
    - section:  DEFAULT
      option:   libvirt_user_virtio_for_bridges
      value:    True
    - section:  DEFAULT
      option:   verbose
      value:    True
    - section:  DEFAULT
      option:   ec2_private_dns_show_ip
      value:    True
    - section:  DEFAULT
      option:   api_paste_config
      value:    /etc/nova/api-paste.ini
    - section:  DEFAULT
      option:   enabled_apis
      value:    ec2,osapi_compute,metadata
    - section:  DEFAULT
      option:   rpc_backend
      value:    rabbit
    - section:  DEFAULT
      option:   rabbit_host
      value:    "{{ inventory_hostname }}"
    - section:  DEFAULT
      option:   rabbit_password
      value:    "{{ rabbitmq_password }}"
    - section:  DEFAULT
      option:   rabbit_userid
      value:    "{{ rabbitmq_user }}"
    - section:  DEFAULT
      option:   auth_strategy
      value:    keystone

    - section:  database
      option:   connection
      value:    mysql://nova:{{ nova_dbpassword }}@{{ inventory_hostname }}/nova
    
    - section:  keystone_authtoken
      option:   auth_uri
      value:    http://{{ inventory_hostname }}:5000/v2.0
    - section:  keystone_authtoken
      option:   identity_uri
      value:    http://{{ inventory_hostname }}:35357
    - section:  keystone_authtoken
      option:   admin_tenant_name
      value:    service
    - section:  keystone_authtoken
      option:   admin_user
      value:    nova
    - section:  keystone_authtoken
      option:   admin_password
      value:    "{{ nova_admin_password }}"

    - section:  glance
      option:   host
      value:    "{{ inventory_hostname }}"

# Configure this for Neutron
    - section:  DEFAULT
      option:   network_api_class
      value:    nova.network.neutronv2.api.API
    - section:  DEFAULT
      option:   security_group_api
      value:    neutron
    - section:  DEFAULT
      option:   linuxnet_interface_driver 
      value:    nova.network.linux_net.LinuxOVSInterfaceDriver
    - section:  DEFAULT
      option:   firewall_driver
      value:    nova.virt.firewall.NoopFirewallDriver

    - section:  neutron
      option:   url
      value:    http://{{ inventory_hostname }}:9696
    - section:  neutron
      option:   auth_strategy
      value:    keystone
    - section:  neutron
      option:   admin_auth_url
      value:    http://{{ inventory_hostname }}:35357/v2.0
    - section:  neutron
      option:   admin_tenant_name
      value:    service
    - section:  neutron
      option:   admin_username
      value:    neutron
    - section:  neutron
      option:   admin_password
      value:    "{{ neutron_admin_password }}"
    - section:  neutron
      option:   service_metadata_proxy
      value:    True
    - section:  neutron
      option:   metadata_proxy_shared_secret
      value:    "{{ metadata_shared_secret }}"


 # notify:
 #   - Sync Nova Database
 #   - Restart Nova Server 
- name: Sync Nova Database
  shell: /bin/sh -c "nova-manage db sync" nova

- name: Restart Nova Server 
  service: name={{ item }} state=restarted
  with_items: 
    - nova-api
    - nova-cert
    - nova-consoleauth
    - nova-scheduler
    - nova-conductor
    - nova-novncproxy
