# installs the things i need for the openstack controller node
# MariaDB hints: https://mariadb.com/blog/devops-mariadb-part-1
---
- name: Ensure RabbitMQ Server is installed
  apt: name=rabbitmq-server

- name: Set Rabbit MQ user Password
  rabbitmq_user: user={{ rabbitmq_user }} 
                 password={{ rabbitmq_password }}
                 vhost=/
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present
  register: result
- name: Remove guest user
  rabbitmq_user: user=guest state=absent

- name: Restart RabbitMQ service
  service: name=rabbitmq-server state=restarted
  when: result|changed
