# installs the things i need for a basic Ubuntu Image. 
---
- name: Make sure /etc/apt/sources.list is right.  (xCAT install changes it)
  copy: >
    src=../files/sources.list 
    dest=/etc/apt/sources.list

- name: Make sure proxy is set for apt
  copy: >
    src=../files/80proxy
    dest=/etc/apt/apt.conf.d/80proxy

- name: Add Juno repo
  apt_repository: repo="deb http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/juno main"
  register: result

- name: Add keyring
  apt: name=ubuntu-cloud-keyring

- name: Update Everything
  apt: upgrade=full update_cache=yes
  when: result|success

- name: Update Distribution
  apt: upgrade=dist force=yes 
  when: result|success

- name: Install a bunch of Items
  apt: name={{ item }} state=present
  with_items:
    - vim
    - python-software-properties
    - software-properties-common 
    - qemu-kvm 
    - libvirt-bin 
    - ubuntu-vm-builder 
    - bridge-utils

- name: Get hostname last number
  shell: hostname | awk -F 0 '{print $2 }'
  register: last_octet

- name: Setup Ethernet Network
  template: src=../templates/interfaces.js dest=/etc/network/interfaces
  register: result

- name: Restart interfaces 
  shell: ifup br-ex && ifconfig eth0 0
  when: result|success
