---
keystone_dbpassword: Cisco.123
glance_dbpassword: Cisco.123
admin_token: 7931ba7e7ba88e90b3e1
keystone_admin_password: Cisco.123
glance_admin_password: Cisco.123
rabbitmq_password: Cisco.123

# snagged from: https://github.com/dguerri/openstack-keystone/blob/master/vars/main.yml
openstack_service_env:
  OS_SERVICE_TOKEN: "{{ admin_token }}"
  OS_SERVICE_ENDPOINT: "http://{{ inventory_hostname }}:35357/v2.0"
